### PR TITLE
checkers: Add checker for Janet

### PR DESCRIPTION
**Pull request by alternateved**
Hello!

I would like to add support for Janet checker.

### CODE REVIEW

**Comment by alternateved** [comment]
Hmm, I'm not entirely sure why installer file cannot be run in pipeline:
```
#12 82.39 find: 'installers/janet.bash': Permission denied
```

I don't have docker installed (and it would be hard for me to do so on this machine) so I cannot test that locally.

**Comment by mohkale** [comment]
@alternateved 

Looks like it's because the installer is not executable. You'll wanna run `chmod +x` on it.

```text
(HEAD) λ stat janet.bash
  File: janet.bash
  Size: 265             Blocks: 8          IO Block: 4096   regular file
Device: 8,17    Inode: 17098924    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ mohkale)   Gid: ( 1001/ mohkale)
Access: 2024-09-02 20:31:27.589757645 +0100
Modify: 2024-09-02 20:31:27.563090934 +0100
Change: 2024-09-02 20:31:27.563090934 +0100
 Birth: 2024-09-02 20:31:27.563090934 +0100

```

**Comment by alternateved** [comment]
Thanks! I was scratching my head on that while solution was that simple.

**Review by mohkale — APPROVED** [review]
LGTM :-). Extra thank you for adding tests.

**Pull request merged**
